CREATE TABLE USER_PROFILE (
	USER_ID Integer not null,
	NAME varchar(32),
	NAME_FONT_COLOR varchar(8),
	NAME_FONT_SIZE Integer,
	TITLE varchar(128),
	TITLE_FONT_COLOR varchar(8),
	TITLE_FONT_SIZE Integer,
	CONTENT varchar(2048),
	CONTENT_FONT_COLOR varchar(8),
	CONTENT_FONT_SIZE Integer,
	PROFILE_BOX_COLOR varchar(8),
	PROFILE_BOX_TRANSPARENT boolean,
	PROFILE_BOX_POSITION varchar(16),
	BG_IMG_URL varchar(512),
	BG_IMG_LAYOUT varchar(8),
	primary key (USER_ID),
	FOREIGN KEY (USER_ID) REFERENCES USER_MASTER(ID));