CREATE TABLE USER_PROFILE (
	ID Integer not null,
	NAME varchar(32) not null,
	NAME_FONT_COLOR varchar(8) not null,
	NAME_FONT_SIZE Integer not null,
	TITLE varchar(128),
	TITLE_FONT_COLOR varchar(8),
	TITLE_FONT_SIZE Integer,
	CONTENT varchar(2048),
	CONTENT_FONT_COLOR varchar(8),
	CONTENT_FONT_SIZE Integer,
	PROFILE_BOX_COLOR varchar(8) not null,
	PROFILE_BOX_OPACITY Integer not null,
	PROFILE_BOX_POSITION varchar(8) not null,
	BG_IMG_URL varchar(512),
	BG_IMG_LAYOUT varchar(8),
	primary key (ID),
	FOREIGN KEY (ID) REFERENCES USER_MASTER(ID));