CREATE TABLE USER_MASTER (
	ID Integer not null,
	EMAIL varchar(128) not null,
	CRYPTO_PASSWORD varchar(32) not null,
	NAME varchar(32) not null,
	NAME_FONT_COLOR varchar(8) not null,
	NAME_FONT_SIZE Integer not null,
	TITLE varchar(128) not null,
	TITLE_FONT_COLOR varchar(8) not null,
	TITLE_FONT_SIZE Integer not null,
	CONTENT varchar(2048) not null,
	CONTENT_FONT_COLOR varchar(8) not null,
	CONTENT_FONT_SIZE Integer not null,
	PROFILE_BOX_COLOR varchar(8) not null,
	PROFILE_BOX_OPACITY Integer not null,
	PROFILE_BOX_POSITION varchar(8) not null,
	BG_IMG_URL varchar(512),
	BG_IMG_LAYOUT varchar(8),
	primary key (ID));
CREATE UNIQUE INDEX USER_EMAIL_IDX ON USER_MASTER(EMAIL);